apiVersion: v1
appVersion: "8.1"
description: MOLGENIS Helm chart for the frontend
name: molgenis-frontend
version: 1.2.0
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://github.com/molgenis/molgenis-ops-helm/raw/master/charts/molgenis-frontend/catalogIcon-molgenis-frontend.png
home: https://www.molgenis.org
maintainers:
- name: sidohaakma
- name: fdlk
