# Default values for molgenis-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# abs gives details of the credentials to reach the azure backup storage
abs:
  # account is the name of the Storage account
  account: fdlkops
  # access key for the Storage account
  accessKey: xxxx
  # default cloud
  cloud: AzurePublicCloud

# backupjob describes the backup cronjob
backupJob:
  # enable enables the backup job
  enable: true
  # schedule gives the cron schedule for the backup job
  schedule: "0 12 * * 1"

###
# All of the config variables related to setting up the etcd-operator
# If you want more information about the variables exposed, please visit:
#   https://github.com/kubernetes/charts/tree/master/stable/etcd-operator#configuration
###
etcd-operator:
  deployments:
    etcdOperator: true
    backupOperator: true
    restoreOperator: true
  serviceAccount:
    etcdOperatorServiceAccount:
      create: true
    backupOperatorServiceAccount:
      create: true
    restoreOperatorServiceAccount:
      create: true
  etcdOperator:
    image:
      tag: v0.9.2
  backupOperator:
    image:
      tag: v0.9.2
  restoreOperator:
    image:
      tag: v0.9.2

vault-operator:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi

ui:
  name: "vault-ui"
  replicaCount: 1
  image:
    repository: djenriquez/vault-ui
    tag: latest
  service:
    name: vault-ui
    type: ClusterIP
    externalPort: 8000
    internalPort: 8000
    # nodePort: 32001
  ingress:
    enabled: true
    # Used to create Ingress record (should used with service.type: ClusterIP).
    host: vault.molgenis.org
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 25m
      memory: 250Mi
  nodeSelector:
    deployPod: "true"
  vault:
    auth: GITHUB
    url: https://vault.vault-operator:8200
