apiVersion: v1
appVersion: "1.0"
description: A Hubot for MOLGENIS
name: molgenis-hubot
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
home: https://hubot.github.com/
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-hubot/catalogIcon-molgenis-hubot.png
version: 0.2.2
maintainers:
- name: fdlk
- name: sidohaakma
