apiVersion: v1
appVersion: "1.0"
description: Services for a MOLGENIS Armadillo cohort
name: molgenis-armadillo-cohort
home: https://molgenis.org
version: 0.1.0
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-armadillo/catalogIcon-molgenis-armadillo.png
maintainers:
- name: fdlk
- name: sidohaakma