{{- if .Values.postgres.enabled }}
{{- if .Values.persistence.enabled }}
apiVersion: extensions/v1beta1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.postgres.persistence.claim }}
  annotations:
    {{- if .Values.persistence.retain }}
    volume.beta.kubernetes.io/storage-class: "nfs-provisioner-retain"
    {{- else }}
    volume.beta.kubernetes.io/storage-class: "nfs-provisioner"
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
    {{- if eq .Values.persistence.postgres.size "default" }}
      {{- if eq .Values.molgenis.type.kind "small" }}
      storage: {{ .Values.postgres.type.small.persistence.size }}
      {{- else if eq .Values.molgenis.type.kind "medium" }}
      storage: {{ .Values.postgres.type.medium.persistence.size }}
      {{- else }}
      storage: {{ .Values.postgres.type.large.persistence.size }}
      {{- end }}
    {{ else }}
        storage: {{ .Values.persistence.postgres.size }}
    {{- end }}
{{- end }}
{{- end }}