apiVersion: v1
appVersion: "1.0"
description: MOLGENIS Helm chart for the website
name: molgenis-website
version: 0.4.0
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://github.com/molgenis/molgenis-ops-helm/raw/master/charts/molgenis-website/catalogIcon-molgenis-website.png
home: https://www.molgenis.org
maintainers:
- name: sidohaakma
- name: fdlk
