apiVersion: v1
appVersion: "7.5.2"
description: A Helm chart for elesticsearch and kibana configured for getting logs from the Molgenis instances
name: molgenis-logging
version: 0.5.2
home: https://github.com/molgenis/molgenis-ops-helm
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-logging/catalogIcon-molgenis-logging.png
maintainers:
  - name: ChristianHilbrands
  - name: fdlk
  - name: tommydeboer
