apiVersion: v1
appVersion: "7.2.0"
description: A Helm chart for elesticsearch and kibana configured for getting logs from the Molgenis instances
name: molgenis-logging
version: 0.1.2
home: https://github.com/molgenis/molgenis-ops-helm
maintainers:
  - name: ChristianHilbrands
