apiVersion: v2
name: molgenis-grafana
home: https://grafana.net
version: 1.1.0
appVersion: 8.3.1
dependencies:
  - name: grafana
    version: 6.19.1
    repository: https://grafana.github.io/helm-charts
description: Molgenis installation for the Grafana chart.
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-grafana/catalogIcon-molgenis-grafana.png
maintainers:
- name: fdlk
- name: sidohaakma
- name: christianhilbrands
