apiVersion: v1
appVersion: "0.13.4"
description: KES is a simple, stateless and distributed key-management system
name: kes
version: 0.1.0
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/kes/catalogIcon-kes.png
home: http://molgenis.org
maintainers:
- name: fdlk
- name: sidohaakma
