{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-ingress"
  labels:
    app: {{ template "nexus.name" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" $.Values.ingress.pathUi }}
          backend:
            serviceName: "{{ $.Release.Name }}-{{ $.Values.nexus.name }}-svc"
            servicePort: {{ $.Values.nexus.port.ui }}
        - path: {{ default "/v1" $.Values.ingress.pathDockerV1 }}
          backend:
            serviceName: "{{ $.Release.Name }}-{{ $.Values.nexus.name }}-svc"
            servicePort: {{ $.Values.nexus.port.docker }}
        - path: {{ default "/v2" $.Values.ingress.pathDockerV2 }}
          backend:
            serviceName: "{{ $.Release.Name }}-{{ $.Values.nexus.name }}-svc"
            servicePort: {{ $.Values.nexus.port.docker }}
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
{{- end }}
---
{{- end }}
{{- end }}