apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-{{ .Values.nexus.name }}-svc"
  labels:
    app: {{ template "nexus.name" . }}
    chart: {{ template "nexus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.nexus.service.type }}
  ports:
  - name: ui
    port: {{ .Values.nexus.port.ui }}
  - name: docker
    port: {{ .Values.nexus.port.docker }}
  selector:
    app: {{ .Values.nexus.selector }}
    release: {{ .Release.Name }}
