apiVersion: v1
appVersion: "1.0"
description: Opencpu stack for MOLGENIS
name: molgenis-opencpu
version: 0.3.1
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-opencpu/catalogIcon-molgenis-opencpu.png
home: https://www.opencpu.org
maintainers:
- name: sidohaakma
- name: fdlk
