# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

nexus:
  name: nexus
  strategy:
    type: Recreate
  restartPolicy: Always
  image:
    repository: registry.hub.docker.com
    name: sonatype/nexus3
    tag: 3.22.0
    pullPolicy: IfNotPresent
  port:
    docker: 5000
    ui: 8081
  service:
    type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  pathDockerV1: /v1
  pathDockerV2: /v2
  pathUi: /
  hosts:
  - name: registry.molgenis.org
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteMany
  size: 500Gi
  # existingClaim: ""

resources: {}

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
