# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

nexus:
  name: nexus
  strategy:
    type: Recreate
  selector: nexus
  restartPolicy: Always
  image:
    repository: registry.hub.docker.com
    name: molgenis/nexus3
    tag: latest
    pullPolicy: Always
  port:
    docker: 5000
    ui: 8081
  service:
    type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  pathDockerV1: /v1
  pathDockerV2: /v2
  pathUi: /
  hosts:
  - name: registry.molgenis.org
  tls: []

persistence:
  retain: true
  enabled: true
  claim: pvc-molgenis-nexus
  size: 500Gi


resources: {}

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
