apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  labels:
    app: molgenis-logging
    chart: Chart.yml
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  username: {{ .Values.elasticsearch.authentication.username | quote }}
  password: {{ .Values.elasticsearch.authentication.password | b64enc }}
