dependencies:
  - name: molgenis-elasticsearch
    version: 1.0.0
    repository: https://registry.molgenis.org/repository/helm
    condition: molgenis-elasticsearch.enabled
  - name: postgresql
    version: 3.10.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgres.enabled
  - name: minio
    version: 2.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: minio.enabled