apiVersion: v1
name: molgenis-jenkins
home: https://jenkins.io/
version: 1.14.0
appVersion: "2.263"
description: Molgenis installation for the jenkins chart.
sources:
  - https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-jenkins/catalogIcon-molgenis-jenkins.png
maintainers:
  - name: fdlk
  - name: sidohaakma
