# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

opencpu:
  name: opencpu
  strategy:
    type: Recreate
  restartPolicy: Always
  image:
    repository: registry.hub.docker.com
    name: molgenis/opencpu
    tag: stable
    pullPolicy: Always
  service:
    name: opencpu
    type: LoadBalancer
    port: 8004
    firewall:
    - 145.100.224.1/24

ingress:
  enabled: false
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  }
  path: /
  hosts:
  - name: opencpu.molgenis.org
  tls: []

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
